#!/usr/bin/env bash

# Copyright (c) 2023-present, Дід Alik and the Kids {{{1
#
# This script is licensed under the Apache License, Version 2.0, found in the
# LICENSE file in the root directory of this source tree.
##

ERR=err.log # {{{1
OUT=latest_test.html

teardown () { # {{{1
  [ -e .pids2kill ] && while read;do kill $REPLY;done <.pids2kill
  kill $PID_OF_TAIL
  echo "- teardown killed PID_OF_TAIL $PID_OF_TAIL" >> $ERR
  exit $EXIT_CODE
}
trap teardown EXIT

rm -f .pids2kill $OUT $ERR # {{{1 
touch $OUT
tail -n 999999 -f $OUT &
PID_OF_TAIL=$!

#rm -rf build #  TODO uncomment when done with DEV        # {{{1
             ## Comment out to use the current poc build ##
../bin/poc.mjs $@ >> $OUT 2>>$ERR # {{{1
EXIT_CODE=$?

cat >> $OUT << HTML_TAIL

</pre><samp><h3>The PoC demo stopped on $(date)</h3></samp></body></html> 
HTML_TAIL
exit $EXIT_CODE

# With thanks to: {{{1
# - https://stackoverflow.com/questions/1521462/looping-through-the-content-of-a-file-in-bash
# - https://stellar.stackexchange.com/questions/5847/tx-too-late-error-on-every-transaction-with-a-set-timeout
# - https://tecadmin.net/setup-time-synchronisation-ntp-server-on-ubuntu-linuxmint/
#
##
