# The Stellar Help Exchange info file
VERSION="2.0.0"

NETWORK_PASSPHRASE="Public Global Stellar Network ; September 2015"
ACCOUNTS=[
GC7BFT2ZXIQAU2GAYNODPVJV4OBFECV5L3NKO4RV5SHXFUR24M3BZNPY
]

[DOCUMENTATION]

[[PRINCIPALS]]

[[CURRENCIES]]
code="HEXA"
issuer="GC7BFT2ZXIQAU2GAYNODPVJV4OBFECV5L3NKO4RV5SHXFUR24M3BZNPY"
is_asset_anchored=false

[[CURRENCIES]]
code="ClawableHexa"
issuer="GC7BFT2ZXIQAU2GAYNODPVJV4OBFECV5L3NKO4RV5SHXFUR24M3BZNPY"
is_asset_anchored=false
