#!/usr/bin/env bash

# Copyright (c) 2023-present, Дід Alik and the Kids {{{1
#
# This script is licensed under the Apache License, Version 2.0, found in the
# LICENSE file in the root directory of this source tree.
##

LOCALDEV_LOG=error.log # {{{1

teardown () { # {{{1
  [ -e .pids2kill ] && while read;do kill $REPLY;done <.pids2kill
  kill $PID_OF_TAIL
  echo "- teardown killed PID_OF_TAIL $PID_OF_TAIL" >> $LOCALDEV_LOG
}
trap teardown EXIT

rm -f .pids2kill loop.log $LOCALDEV_LOG # {{{1 
touch loop.log
tail -n 999999 -f loop.log &
PID_OF_TAIL=$!

. ../config.env

$RUN_MJS setup_it >> loop.log 2>>$LOCALDEV_LOG # {{{1

cd ..
rm -rf dev/build
npm run dev --dir=prod/fix --run=issuer >> qa/loop.log 2>>qa/$LOCALDEV_LOG
cd -

cat >> loop.log << HTML_TAIL

</pre><samp><h3>Integration tests stopped on $(date)</h3></samp></body></html> 
HTML_TAIL
EXIT_CODE=$?
exit $EXIT_CODE

# With thanks to: {{{1
# - https://stackoverflow.com/questions/1521462/looping-through-the-content-of-a-file-in-bash
#
##
